name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  Release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.19

      - name: Build
        id: build
        run: |
          go run ./cmd/cnip

      - name: Upload to release branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: release
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
